### ISSUE TITLE
Creación de página estática 'Nosotros'

### ISSUE THREAD

**Issue by pepcerda** [Three-Points/LaRifamos-Frontend#7]
### ℹ️ Resumen
> Se creará la página estática 'Nosotros' , el contenido de la cual se agregará a un componente de React /pages/nosotrosPage.jsx 

### 🚧Criterio de aceptación
- Se podrá visualizar la página estática 'Nosotros' añadiendo el componente nosostrosPage.jsx en App.js del proyecto.

**Comment by manuel1581** [comment]
Se agrego una pagina html estatica... acabo de leer las instrucciones de Josep, las corregire para usarlo con el componente de react en mi proximo commit.

**Comment by manuel1581** [comment]
agregue el aboutUs ahora en .jsx
