### ISSUE TITLE
Creación de la página estática 'Privacidad' 

### ISSUE THREAD

**Issue by pepcerda** [Three-Points/LaRifamos-Frontend#8]
### ℹ️ Resumen
> Se creará la página estática 'Privacidad' , el contenido de la cual se agregará a un componente de React /pages/privacidadPage.jsx 

### 🚧Criterio de aceptación
- Se podrá visualizar la página estática 'Privacidad' añadiendo el componente privacidadPage.jsx en App.js del proyecto.

**Comment by manuel1581** [comment]
se agrego pagina estatica privacidadPage.jsx
