### ISSUE TITLE
Creación de la página estática 'Términos y Condiciones' 

### ISSUE THREAD

**Issue by pepcerda** [Three-Points/LaRifamos-Frontend#9]
### ℹ️ Resumen
> Se creará la página estática 'Términos y Condiciones' , el contenido de la cual se agregará a un componente de React /pages/terminosPage.jsx 

### 🚧Criterio de aceptación
- Se podrá visualizar la página estática 'Términos y Condiciones' añadiendo el componente terminosPage.jsx en App.js del proyecto.

**Comment by manuel1581** [comment]
se anade .jsx terminosPage
